### ISSUE TITLE
Not showing appropiate error message when assignment uploading goes wrong on teacher's end.

### ISSUE THREAD

**Issue by muneeb-art** [LMS-Discussion/LMS-Discussion#11]
![Screenshot 2020-10-15 155250](https://user-images.githubusercontent.com/68659096/96114049-858ca080-0efe-11eb-8859-2714cab0f1a2.png)
It never tells what actually went wrong....does it not support the file format or file is too big to upload etc ??

**Comment by MuhmmadAsjid** [comment]
transferred to main repo
