### ISSUE TITLE
Uploading Assignment

### ISSUE THREAD

**Issue by HinaFiaz69** [LMS-Discussion/LMS-Discussion#12]
In Teacher's login, Mark Assessment->assignment->upload assignment, even though nothing is given it still uploads the assignment and 'due date of assignment' below the 'due date' text box shows no purpose.

![Screenshot (114)](https://user-images.githubusercontent.com/72910439/96114352-ee741880-0efe-11eb-9e27-018fa714d6f4.png)

**Comment by MuhmmadAsjid** [comment]
transferred to main repo
